[window]
dimensions = { columns = 85, lines = 25 }

[font]
normal = { family = "Terminus", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

# my own colorscheme:
[colors.primary]
foreground  = "#ffffff"
background  = "#003644"

[colors.normal]
black    = "#1e1e1e"
red      = "#ed1515"
green    = "#11d116"
yellow   = "#fdd300"
blue     = "#1d80ff"
magenta  = "#ff6923"
cyan     = "#00ffff"
white    = "#ffffff"

[colors.bright]
black    = "#5e5e5e"
red      = "#ed1515"
green    = "#11d116"
yellow   = "#fffb29"
blue     = "#5fd7ff"
magenta  = "#0ff000"
cyan     = "#c78fff"
white    = "#ffffff"
